service:
  name: cvs-svc-stum-crm-test-station

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs8.10
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  getTestStations:
    handler: src/handler.handler
    events:
      - http:
          path: test-stations
          method: get
      - http:
          path: test-stations/{testStationPNumber}
          method: get
          request:
            parameters:
              paths:
                testStationPNumber: true

custom:
  serverless-offline:
    port: 3004
  dynamodb:
    stages:
      - dev
    start:
      port: 8007
      inMemory: true
      migrate: true
      seed: true
      noStart: false
    seed:
      test-stations:
        sources:
          - table: cvs-local-test-stations
            sources: [./tests/resources/test-stations.json]

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-test-stations
        AttributeDefinitions:
        - AttributeName: testStationId
          AttributeType: S
        - AttributeName: testStationPNumber
          AttributeType: S
        KeySchema:
        - AttributeName: testStationId
          KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: testStationPNumberIndex
            KeySchema:
              - AttributeName: testStationPNumber
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - testStationEmails
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
